sudo: false
cache: pip

addons:
  apt:
   sources:
      - pov-wkhtmltopdf
   packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow
      - wkhtmltopdf

language: python

python:
  - "2.7"

env:
  - VERSION="7.0" LINT_CHECK="1"
  - VERSION="7.0" ODOO_REPO="odoo/odoo" LINT_CHECK="0"
  - VERSION="7.0" ODOO_REPO="OCA/OCB" LINT_CHECK="0"

virtualenv:
  system_site_packages: true

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - git clone https://github.com/OCA/webkit-tools.git ${HOME}/webkit-tools -b ${VERSION}
  - sudo apt-get install xfonts-75dpi
  - sudo wget http://sourceforge.net/projects/wkhtmltopdf/files/0.12.2.1/wkhtmltox-0.12.2.1_linux-precise-amd64.deb -P /tmp/
  - sudo dpkg -i /tmp/wkhtmltox-0.12.2.1_linux-precise-amd64.deb
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
